#! /bin/sh

if [ ! command -v wget 2>&1 >/dev/null ]; then
    echo "wget could not be found, can not proceed"
    exit 1
fi

if [ ! command -v unzip 2>&1 >/dev/null ]; then
    echo "unzip could not be found, can not proceed"
    exit 1
fi

if [ ! -f ./torch-server.zip ]; then
  wget https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip
fi

if [ ! -d ./torch-server ]; then
  unzip -d torch-server torch-server.zip 
fi


if [ "$(stat -c '%u' torch-server)" != "1000" ]; then
    echo "Setting owner of torch-server to UID 1000"
    sudo chown -R 1000:1000 torch-server
fi

sudo docker-compose up -d && sudo docker-compose logs -f